### PR TITLE
Feature/lever

### PR DESCRIPTION
**Pull request by gre-v-el**
* Added a lever. Player can pull it by walking through it.
* Added on/off indication (the effect is a matter to change, but the mechanism is there)
* Modified the moving platform prefab to accept lever events
* Added a lever test level with moving platforms controlleb by levers.

### CODE REVIEW

**Comment by gre-v-el** [comment]
This branch is coming from the `lab-2` branch, so it should be merged **after** *or* **instead of** `lab-2`

**Comment by kitty-ku** [comment]
Voting for merging **instead**.

**Comment by ThreeCoffees** [comment]
I also vote instead.

**Review by ThreeCoffees — APPROVED** [review]
Wyszło super.

**Pull request merged**
